name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make build-dir
      run: mkdir build
    - name: compile
      run: cd build && g++ -O3 -o Exodus.out ../main.cpp
    - name: clean
      run: strip build/Exodus.out
    - name: Github Release
      uses: elgohr/Github-Release-Action@v3.1
      env:
          GHR_PATH: build/Exodus.out
          GITHUB_TOKEN: ${{ secrets.GITOK }}
