name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make build-dir
      run: mkdir build
    - name: compile
      run: cd build && g++ -O3 -o Exodus.out ../main.cpp
    - name: clean
      run: strip build/Exodus.out
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: Build\Exodus.out
      env:
        GITHUB_TOKEN: ${{ secrets.GITOK }}
